In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3], dtype = complex)

In [5]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
a.dtype

dtype('complex128')

In [10]:
a.itemsize

16

In [11]:
# zeros | creates a new array filled completely with zeros based on the shape and data type you choose.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# ones | creates a new array filled with the value one
np.ones((3,3), dtype= int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
# empty | creates a new array of a specified shape and type without initializing its entries to any specific values i.e random values
np.empty((3,4), dtype = int)

array([[   138953548,            0, 425201762421, 137438953576],
       [450971566182, 433791697004, 476741369888, 137438953586],
       [450971566180, 433791697010, 498216206435, 489626271855]])