In [1]:
import numpy as np

In [2]:
# arange | returns a 1D NumPy array (ndarray) containing evenly spaced values within a specified interval.
# arange(start,end,step)
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [3]:
a = np.arange(1,20,2.7)
a

array([ 1. ,  3.7,  6.4,  9.1, 11.8, 14.5, 17.2, 19.9])

The np.linspace() function in Python's NumPy library returns an array of evenly (linearly) spaced numbers over a specified interval. Instead of choosing the step size, you tell it how many numbers you want, and NumPy automatically calculates the exact spacing.

In [4]:
# linspace | linspace(start, end, no.of elements)
b = np.linspace(1,10,6)
b

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [5]:
# arange | reshape()
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# 3D arary
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])